"""add payment appointment relation

Revision ID: b5aa047e3016
Revises: 672435e5ba1c
Create Date: 2026-09-03 12:29:15.306832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5aa047e3016'
down_revision: Union[str, Sequence[str], None] = '672435e5ba1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_table('payments')
    op.drop_index(op.f('ix_doctor_leave_doctor_id'), table_name='doctor_leave')
    op.drop_index(op.f('ix_doctor_leave_id'), table_name='doctor_leave')
    op.drop_table('doctor_leave')
    op.drop_index(op.f('ix_doctor_availability_id'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('appointment_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('appointments_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey')),
    sa.UniqueConstraint('doctor_id', 'appointment_date', 'appointment_time', name=op.f('uq_doctor_appointment_slot'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('slot_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_availability_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_availability_pkey')),
    sa.UniqueConstraint('doctor_id', 'date', 'start_time', 'end_time', name=op.f('uq_doctor_availability'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_doctor_availability_id'), 'doctor_availability', ['id'], unique=False)
    op.create_table('doctor_leave',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('leave_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('doctor_leave_doctor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_leave_pkey')),
    sa.UniqueConstraint('doctor_id', 'leave_date', name=op.f('uq_doctor_leave'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_doctor_leave_id'), 'doctor_leave', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_leave_doctor_id'), 'doctor_leave', ['doctor_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('payments_razorpay_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('razorpay_payment_id', name=op.f('payments_razorpay_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('user_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_permissions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'permission_id', name=op.f('uq_user_permission'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    # ### end Alembic commands ###
